#!/bin/sh

readonly IPC=/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock

{
	hyprctl -j monitors
	socat -u UNIX-CONNECT:"$IPC" - | while read -r _
	do
		case "${_%>>*}" in
		workspace|moveworkspace)
			hyprctl -j monitors
		esac
	done
} | jq -cr '[.[] | .activeWorkspace.id % 10]'
