#!/bin/sh

while :
do
	# {
	# 	date +'%A, %-d of %B %Y — %T %Z'
	# 	TZ='Asia/Kolkata' date +'(%T %Z)'
	# } | paste -sd ' '
	date +'%A, %-d of %B %Y — %H:%M %Z'
	sleep 10
	# sleep "$(date +'%s.%N' | dc -e '? d 1 + 1 / r - p')"
done | ordinal -p1
