#!/bin/sh

readonly IPC=/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock

hyprctl devices -j | jq -r '.keyboards[-1].active_keymap'
socat -u UNIX-CONNECT:"$IPC" - | sed -En 's/^activelayout>>[^,]+,//p'
