#!/bin/sh

readonly IPC=/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock

spaces="`hyprctl -j workspaces | jq -r 'sort_by(.id) | .[] | .name'`"
jo -a $spaces

socat -u UNIX-CONNECT:"$IPC" - \
	| stdbuf -oL grep -E '^(create|destroy)workspace>>' \
	| while IFS='>>' read -r e _ n
	do
		case "$e" in
		c*)
			spaces="`printf '%s\n%s\n' "$spaces" $n | sort -V`"
			;;
		d*)
			spaces="`echo "$spaces" | grep -v "^$n$"`"
			;;
		esac
		jo -a $spaces
	done
