[main]
font=Iosevka Smooth Term:size=17
pad=8x8

[cursor]
blink=no

# Mango Dark
[colors]
foreground=D1D5D8               # fg-main
background=2B303B               # bg-main

regular0=1D232F                 # bg-dim
regular1=F24E4E                 # red-main
regular2=A6E22E                 # green-main
regular3=E5D070                 # yellow-main
regular4=569CD6                 # blue-main
regular5=E183E8                 # magenta-main
regular6=7DC1E6                 # cyan-main
regular7=D1D5D8                 # fg-main

bright0=414859                  # bg-bright
bright1=FF7373                  # red-bright
bright2=C4F553                  # green-bright
bright3=FFEE99                  # yellow-bright
bright4=85C5FF                  # blue-bright
bright5=FFACFF                  # magenta-bright
bright6=A8E0FF                  # cyan-bright
bright7=F0F4F8                  # fg-bright

dim0=1D232F                     # bg-dim
dim1=A42A22                     # red-dim
dim2=7BAF20                     # green-dim
dim3=B8A349                     # yellow-dim
dim4=427EB3                     # blue-dim
dim5=A151A6                     # magenta-dim
dim6=569BBB                     # cyan-dim
dim7=939CA8                     # fg-dim

selection-foreground=F0F4F8     # fg-bright
selection-background=414859     # bg-bright
urls=7DC1E6                     # cyan-main

# Mango Light
[colors2]
foreground=2E3440               # fg-main
background=FAFBFC               # bg-main

regular0=2E3440                 # fg-main
regular1=B51A22                 # red-main
regular2=286620                 # green-main
regular3=735610                 # yellow-main
regular4=1856B8                 # blue-main
regular5=8828A1                 # magenta-main
regular6=006B8F                 # cyan-main
regular7=E5E9F0                 # bg-dim

bright0=6B7A8F                  # fg-dim
bright1=8A0D14                  # red-bright
bright2=154210                  # green-bright
bright3=523B06                  # yellow-bright
bright4=0D3A82                  # blue-bright
bright5=5C1770                  # magenta-bright
bright6=004761                  # cyan-bright
bright7=FFFFFF                  # bg-bright

dim0=6B7A8F                     # fg-dim
dim1=D44A50                     # red-dim
dim2=42A835                     # green-dim
dim3=A68435                     # yellow-dim
dim4=3B80F2                     # blue-dim
dim5=AD47C7                     # magenta-dim
dim6=009EE6                     # cyan-dim
dim7=FAFBFC                     # bg-main

selection-foreground=181B21     # fg-bright
selection-background=E5E9F0     # bg-dim
urls=006B8F                     # cyan-main

[key-bindings]
scrollback-end=Control+g
search-start=Control+slash

[tweak]
overflowing-glyphs=no