#!/bin/sh

case "$1" in
dark)
	killall -USR1 foot
	;;
light)
	killall -USR2 foot
	;;
*)
	>&2 printf 'Usage: %s light|dark\n' "${0##*/}"
	exit 1
esac

gsettings set org.gnome.desktop.interface color-scheme prefer-$theme
