#!/bin/sh

docmd()
{
	case "$1" in
	dark)
		killall -USR1 foot
		gsettings set org.gnome.desktop.interface color-scheme prefer-dark
		;;
	light)
		killall -USR2 foot
		gsettings set org.gnome.desktop.interface color-scheme prefer-light
		;;
	sync)
		x="$(gsettings get org.gnome.desktop.interface color-scheme)"
		x="${x#\'prefer-}"
		docmd "${x%\'}"
		;;
	*)
		>&2 printf 'Usage: %s light|dark|sync\n' "${0##*/}"
		exit 1
	esac
}

docmd "$1"
