#!/bin/sh

sink="${2:-@DEFAULT_AUDIO_SINK@}"

usage()
{
	>&2 printf 'Usage: %s up|down|toggle [sink]\n' "${0##*/}"
	exit 1
}

roundup()
{
	case $1 in
	0.0?) echo 0.1 ;;
	0.1?) echo 0.2 ;;
	0.2?) echo 0.3 ;;
	0.3?) echo 0.4 ;;
	0.4?) echo 0.5 ;;
	0.5?) echo 0.6 ;;
	0.6?) echo 0.7 ;;
	0.7?) echo 0.8 ;;
	0.8?) echo 0.9 ;;
	0.9?) echo 1.0 ;;
	1.00) echo 1.0 ;;
	esac
}

rounddown()
{
	case $1 in
	0.0?|0.10) echo 0.0 ;;
	0.1?|0.20) echo 0.1 ;;
	0.2?|0.30) echo 0.2 ;;
	0.3?|0.40) echo 0.3 ;;
	0.4?|0.50) echo 0.4 ;;
	0.5?|0.60) echo 0.5 ;;
	0.6?|0.70) echo 0.6 ;;
	0.7?|0.80) echo 0.7 ;;
	0.8?|0.90) echo 0.8 ;;
	0.9?|1.00) echo 0.9 ;;
	esac
}

[ $# -gt 2 ] && usage

case "$1" in
up|down)
	vol="$(wpctl get-volume "$sink" | grab 'x/\d+\.\d+/')"
	wpctl set-volume "$sink" $(round$1 $vol)
	;;
toggle)
	wpctl set-mute "$sink" toggle
	;;
'')
	usage
	;;
*)
	>&2 printf '%s: invalid subcommand — ‘%s’\n' "${0##*/}" "$1"
	usage
esac
