#!/bin/sh

set -e

choice="`timedatectl list-timezones | grep './.' | osel`" \
	&& sudo timedatectl set-timezone "$choice" \
	&& notify "${0##*/}" timezone 'Timezone Changed' \
		"The system timezone was changed to ‘$choice’"
